version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:web
    container_name: myapp-web
    environment:
      - PORT=5000
      - GUNICORN_CMD_ARGS=-w 2 --threads 4 --timeout 60
    ports:
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "python", "-c", "import sys, urllib.request; urllib.request.urlopen('http://localhost:5000/'); sys.exit(0)" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s
